from sqlalchemy import Column, Integer, Boolean, ForeignKey
from app.core.database import Base


class Checklist(Base):
    __tablename__ = "checklist"

    id = Column(Integer, primary_key=True, index=True)
    campus_id = Column(Integer, ForeignKey("campus.id"), nullable=False, index=True)

    # SI 5 - Discapacidad y maternidad (10 ítems)
    si5_rampas = Column(Boolean, default=False)
    si5_banos_accesibles = Column(Boolean, default=False)
    si5_pasamanos = Column(Boolean, default=False)
    si5_ascensores = Column(Boolean, default=False)
    si5_senializacion = Column(Boolean, default=False)
    si5_rutas_accesibles = Column(Boolean, default=False)
    si5_estacionamiento = Column(Boolean, default=False)
    si5_sala_lactancia = Column(Boolean, default=False)
    si5_cambiadores = Column(Boolean, default=False)
    si5_apoyos_visuales = Column(Boolean, default=False)

    # SI 6 - Seguridad (13 ítems)
    si6_extintores = Column(Boolean, default=False)
    si6_alarmas = Column(Boolean, default=False)
    si6_cctv = Column(Boolean, default=False)
    si6_personal_seguridad = Column(Boolean, default=False)
    si6_botones_panico = Column(Boolean, default=False)
    si6_app_emergencia = Column(Boolean, default=False)
    si6_salidas_emergencia = Column(Boolean, default=False)
    si6_sistema_contra_incendios = Column(Boolean, default=False)
    si6_refugios = Column(Boolean, default=False)
    si6_primeros_auxilios = Column(Boolean, default=False)
    si6_iluminacion_emergencia = Column(Boolean, default=False)
    si6_simulacros = Column(Boolean, default=False)
    si6_control_acceso = Column(Boolean, default=False)

    # SI 7 - Salud (10 ítems)
    si7_servicio_medico = Column(Boolean, default=False)
    si7_ambulancia = Column(Boolean, default=False)
    si7_consultorio_dental = Column(Boolean, default=False)
    si7_apoyo_psicologico = Column(Boolean, default=False)
    si7_gimnasio = Column(Boolean, default=False)
    si7_cancha_deportiva = Column(Boolean, default=False)
    si7_agua_potable = Column(Boolean, default=False)
    si7_comedor = Column(Boolean, default=False)
    si7_lactario = Column(Boolean, default=False)
    si7_guarderia = Column(Boolean, default=False)

    # SI 8 - Conservación (14 ítems)
    si8_jardin_botanico = Column(Boolean, default=False)
    si8_banco_semillas = Column(Boolean, default=False)
    si8_invernadero = Column(Boolean, default=False)
    si8_area_conservacion = Column(Boolean, default=False)
    si8_programa_reforestacion = Column(Boolean, default=False)
    si8_inventario_flora = Column(Boolean, default=False)
    si8_inventario_fauna = Column(Boolean, default=False)
    si8_especies_amenazadas = Column(Boolean, default=False)
    si8_programa_reintroduccion = Column(Boolean, default=False)
    si8_corredor_biologico = Column(Boolean, default=False)
    si8_compostaje = Column(Boolean, default=False)
    si8_agricultura_organica = Column(Boolean, default=False)
    si8_investigacion_biodiversidad = Column(Boolean, default=False)
    si8_educacion_ambiental = Column(Boolean, default=False)