"""modelo inicial con auth y multi-campus

Revision ID: 8709be0511a4
Revises: 
Create Date: 2026-09-16 05:51:20.852965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '8709be0511a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=15), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('area_total_m2', sa.Float(), nullable=False),
    sa.Column('poblacion_total', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_id'), 'campus', ['id'], unique=False)
    op.create_index(op.f('ix_campus_usuario_id'), 'campus', ['usuario_id'], unique=False)
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('si5_rampas', sa.Boolean(), nullable=True),
    sa.Column('si5_banos_accesibles', sa.Boolean(), nullable=True),
    sa.Column('si5_pasamanos', sa.Boolean(), nullable=True),
    sa.Column('si5_ascensores', sa.Boolean(), nullable=True),
    sa.Column('si5_senializacion', sa.Boolean(), nullable=True),
    sa.Column('si5_rutas_accesibles', sa.Boolean(), nullable=True),
    sa.Column('si5_estacionamiento', sa.Boolean(), nullable=True),
    sa.Column('si5_sala_lactancia', sa.Boolean(), nullable=True),
    sa.Column('si5_cambiadores', sa.Boolean(), nullable=True),
    sa.Column('si5_apoyos_visuales', sa.Boolean(), nullable=True),
    sa.Column('si6_extintores', sa.Boolean(), nullable=True),
    sa.Column('si6_alarmas', sa.Boolean(), nullable=True),
    sa.Column('si6_cctv', sa.Boolean(), nullable=True),
    sa.Column('si6_personal_seguridad', sa.Boolean(), nullable=True),
    sa.Column('si6_botones_panico', sa.Boolean(), nullable=True),
    sa.Column('si6_app_emergencia', sa.Boolean(), nullable=True),
    sa.Column('si6_salidas_emergencia', sa.Boolean(), nullable=True),
    sa.Column('si6_sistema_contra_incendios', sa.Boolean(), nullable=True),
    sa.Column('si6_refugios', sa.Boolean(), nullable=True),
    sa.Column('si6_primeros_auxilios', sa.Boolean(), nullable=True),
    sa.Column('si6_iluminacion_emergencia', sa.Boolean(), nullable=True),
    sa.Column('si6_simulacros', sa.Boolean(), nullable=True),
    sa.Column('si6_control_acceso', sa.Boolean(), nullable=True),
    sa.Column('si7_servicio_medico', sa.Boolean(), nullable=True),
    sa.Column('si7_ambulancia', sa.Boolean(), nullable=True),
    sa.Column('si7_consultorio_dental', sa.Boolean(), nullable=True),
    sa.Column('si7_apoyo_psicologico', sa.Boolean(), nullable=True),
    sa.Column('si7_gimnasio', sa.Boolean(), nullable=True),
    sa.Column('si7_cancha_deportiva', sa.Boolean(), nullable=True),
    sa.Column('si7_agua_potable', sa.Boolean(), nullable=True),
    sa.Column('si7_comedor', sa.Boolean(), nullable=True),
    sa.Column('si7_lactario', sa.Boolean(), nullable=True),
    sa.Column('si7_guarderia', sa.Boolean(), nullable=True),
    sa.Column('si8_jardin_botanico', sa.Boolean(), nullable=True),
    sa.Column('si8_banco_semillas', sa.Boolean(), nullable=True),
    sa.Column('si8_invernadero', sa.Boolean(), nullable=True),
    sa.Column('si8_area_conservacion', sa.Boolean(), nullable=True),
    sa.Column('si8_programa_reforestacion', sa.Boolean(), nullable=True),
    sa.Column('si8_inventario_flora', sa.Boolean(), nullable=True),
    sa.Column('si8_inventario_fauna', sa.Boolean(), nullable=True),
    sa.Column('si8_especies_amenazadas', sa.Boolean(), nullable=True),
    sa.Column('si8_programa_reintroduccion', sa.Boolean(), nullable=True),
    sa.Column('si8_corredor_biologico', sa.Boolean(), nullable=True),
    sa.Column('si8_compostaje', sa.Boolean(), nullable=True),
    sa.Column('si8_agricultura_organica', sa.Boolean(), nullable=True),
    sa.Column('si8_investigacion_biodiversidad', sa.Boolean(), nullable=True),
    sa.Column('si8_educacion_ambiental', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_campus_id'), 'checklist', ['campus_id'], unique=False)
    op.create_index(op.f('ix_checklist_id'), 'checklist', ['id'], unique=False)
    op.create_table('perfil_sostenibilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('energia_clima', sa.Float(), nullable=True),
    sa.Column('residuos', sa.Float(), nullable=True),
    sa.Column('agua', sa.Float(), nullable=True),
    sa.Column('transporte', sa.Float(), nullable=True),
    sa.Column('educacion_investigacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_sostenibilidad_campus_id'), 'perfil_sostenibilidad', ['campus_id'], unique=True)
    op.create_index(op.f('ix_perfil_sostenibilidad_id'), 'perfil_sostenibilidad', ['id'], unique=False)
    op.create_table('simulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('tipo_intervencion', sa.String(length=50), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('geom_geojson', sa.Text(), nullable=True),
    sa.Column('puntajes_antes', sa.Text(), nullable=True),
    sa.Column('puntajes_despues', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulaciones_campus_id'), 'simulaciones', ['campus_id'], unique=False)
    op.create_index(op.f('ix_simulaciones_id'), 'simulaciones', ['id'], unique=False)
    op.create_table('zonas_verdes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_zonas_verdes_geom', 'zonas_verdes', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_zonas_verdes_campus_id'), 'zonas_verdes', ['campus_id'], unique=False)
    op.create_index(op.f('ix_zonas_verdes_id'), 'zonas_verdes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zonas_verdes_id'), table_name='zonas_verdes')
    op.drop_index(op.f('ix_zonas_verdes_campus_id'), table_name='zonas_verdes')
    op.drop_index('idx_zonas_verdes_geom', table_name='zonas_verdes', postgresql_using='gist')
    op.drop_table('zonas_verdes')
    op.drop_index(op.f('ix_simulaciones_id'), table_name='simulaciones')
    op.drop_index(op.f('ix_simulaciones_campus_id'), table_name='simulaciones')
    op.drop_table('simulaciones')
    op.drop_index(op.f('ix_perfil_sostenibilidad_id'), table_name='perfil_sostenibilidad')
    op.drop_index(op.f('ix_perfil_sostenibilidad_campus_id'), table_name='perfil_sostenibilidad')
    op.drop_table('perfil_sostenibilidad')
    op.drop_index(op.f('ix_checklist_id'), table_name='checklist')
    op.drop_index(op.f('ix_checklist_campus_id'), table_name='checklist')
    op.drop_table('checklist')
    op.drop_index(op.f('ix_campus_usuario_id'), table_name='campus')
    op.drop_index(op.f('ix_campus_id'), table_name='campus')
    op.drop_table('campus')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
