"""agregar uso_academico a zonas verdes

Revision ID: a33924dc2e8b
Revises: 8709be0511a4
Create Date: 2026-09-17 08:41:13.215497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33924dc2e8b'
down_revision: Union[str, Sequence[str], None] = '8709be0511a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zonas_verdes', sa.Column('uso_academico', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zonas_verdes', 'uso_academico')
    # ### end Alembic commands ###
